<?php

class UserAccountRepository {
    // ATTRIBUTES
    private PDO $pdo;

    // CONSTRUCTOR
    public function __construct() {
        // We get the unique instance of the database connection
        $this->pdo = DatabaseConnection::getInstance();
    }

    // METHODS

    // UTILITY METHOD : Convert a database row (associative array) to a UserAccount object
    private function rowToUserAccount(array $row) : UserAccount {
        // We create a new UserAccount object with the data of the row (we use the constructor for the required attributes)
        $userAccount = new UserAccount($row['username'], $row['email'], $row['password_hash']);
        // We set the optional attributes with the setters
        $userAccount->setId($row['id']);
        $userAccount->setUserRole(UserRole::from($row['user_role']));
        $userAccount->setDateJoined(new DateTime($row['date_joined']));

        // Check if last_login is not null before to set it (because it's nullable in the database)
        if ($row['last_login'] !== null) {
            $userAccount->setLastLogin(new DateTime($row['last_login']));
        }
        $userAccount->setIdProfilePic($row['id_profile_pic']);

        return $userAccount;
    }

    // CREATE : Insert a new user account in the database
    public function insert(UserAccount $userAccount) : void {
        // We prepare the SQL request string with named parameters (to avoid SQL injections)
        $sqlRequest = "INSERT INTO user_account (user_role, username, email, password_hash, date_joined, last_login, id_profile_pic)
                    VALUES (:user_role, :username, :email, :password_hash, :date_joined, :last_login, :id_profile_pic); ";

        // We prepare the SQL request with the PDO connection, "this->pdo->prepare()" return a PDOStatement object
        $statement = $this->pdo->prepare($sqlRequest);

        // We execute the SQL request with the data of the user account given as parameter
        $statement->execute([
            // We convert the UserRole enum to string (because in SQLite enum are stored as string)
            'user_role' => $userAccount->getUserRole()->value,

            'username' => $userAccount->getUsername(),
            'email' => $userAccount->getEmail(),
            'password_hash' => $userAccount->getPasswordHash(),

            // We convert the DateTime to string (because in SQLite DateTime are stored as string)
            // we use the format "Y-m-d H:i:s" to store the date and time in the database (ex: "2026-06-01 14:30:00")
            'date_joined' => $userAccount->getDateJoined()->format("Y-m-d H:i:s"),
            // Same for lastLogin but we check if it's null before (because it's nullable in the database)
            'last_login' => $userAccount->getLastLogin() ? $userAccount->getLastLogin()->format("Y-m-d H:i:s") : null,

            'id_profile_pic' => $userAccount->getIdProfilePic()
        ]);

        // We recover the id generated by the DB after the insertion of the new user
        // and we set it to the UserAccount object
        // We force the type of 'id' to int because lastInsertId() return a string"
        $userAccount->setId((int)$this->pdo->lastInsertId());

    }

    // READ [ID] : Get a user account by its id
    public function findById(int $id) : ?UserAccount {
        // We prepare the SQL request string with named parameters (to avoid SQL injections)
        $sqlRequest = "SELECT * FROM user_account WHERE id = :id;";
        // We prepare the SQL request with the PDO connection, "this->pdo->prepare()" return a PDOStatement object
        $statement = $this->pdo->prepare($sqlRequest);
        // We execute the request
        $statement->execute(['id' => $id]);
        // We now fetch the result of the execution and store it in $row
        $row = $statement->fetch();

        // If $row isn't empty we return a UserAccount object using "rowToUserAccount()", else we return null
        return $row ? $this->rowToUserAccount($row) : null;
    }

    // READ [USERNAME] : Get a user account by its username
    public function findByUsername(string $username) : ?UserAccount {
        // We prepare the SQL request string with named parameters (to avoid SQL injections)
        $sqlRequest = "SELECT * FROM user_account WHERE username = :username;";
        // We prepare the SQL request with the PDO connection, "this->pdo->prepare()" return a PDOStatement object
        $statement = $this->pdo->prepare($sqlRequest);
        // We execute the request
        $statement->execute(['username' => $username]);
        // We now fetch the result of the execution and store it in $row
        $row = $statement->fetch();

        // If $row isn't empty we return a UserAccount object using "rowToUserAccount()", else we return null
        return $row ? $this->rowToUserAccount($row) : null;
    }

    // READ [EMAIL] : Get a user account by its email
    public function findByEmail(string $email) : ?UserAccount {
        // We prepare the SQL request string with named parameters (to avoid SQL injections)
        $sqlRequest = "SELECT * FROM user_account WHERE email = :email;";
        // We prepare the SQL request with the PDO connection, "this->pdo->prepare()" return a PDOStatement object
        $statement = $this->pdo->prepare($sqlRequest);
        // We execute the request
        $statement->execute(['email' => $email]);
        // We now fetch the result of the execution and store it in $row
        $row = $statement->fetch();

        // If $row isn't empty we return a UserAccount object using "rowToUserAccount()", else we return null
        return $row ? $this->rowToUserAccount($row) : null;
    }

    // READ [ALL] : Get all user accounts from the database
    public function findAll() : array {
        // Because there is no named parameters (no custom parameters), we don't need to prepare the SQL string before
        $statement = $this->pdo->query("SELECT * FROM user_account;");
        // We get all the rows resulted for our previous query
        $rows = $statement->fetchAll();

        $users = [];
        // We create a UserAccount for each element of the $rows array using "rowToUserAccount()"
        foreach ($rows as $row) {
            $users[] = $this->rowToUserAccount($row);
        }

        // Return an array of UserAccount (if fetchAll() returned 0 row we will return an empty array)
        return $users;
    }


    // UPDATE : Update a user account in the database by its id
    public function update(UserAccount $userAccount) : void {
        // We prepare the SQL request string with named parameters (to avoid SQL injections)
        $sqlRequest = "UPDATE user_account
                    SET user_role = :user_role,
                        username = :username,
                        email = :email,
                        password_hash = :password_hash,
                        last_login = :last_login,
                        id_profile_pic = :id_profile_pic
                    WHERE id = :id;";
        // We prepare the SQL request with the PDO connection, "this->pdo->prepare()" return a PDOStatement object
        $statement = $this->pdo->prepare($sqlRequest);
        // We execute the request
        $statement->execute([
            // We get the enum string value (because in SQLite enum don't exist and are string)
            'user_role' => $userAccount->getUserRole()->value,
            'username' => $userAccount->getUsername(),
            'email' => $userAccount->getEmail(),
            'password_hash' => $userAccount->getPasswordHash(),
            // Check if not null, if not we format it
            'last_login' => $userAccount->getLastLogin() ? $userAccount->getLastLogin()->format('Y-m-d H:i:s') : null,
            'id_profile_pic' => $userAccount->getIdProfilePic(),
            'id' => $userAccount->getId()
        ]);

    }

    // DELETE : Delete a user account from the database by its id
    public function delete(int $id) : void {
        // We prepare the SQL request string with named parameters (to avoid SQL injections)
        $sqlRequest = "DELETE FROM user_account WHERE id = :id";
        // We prepare the SQL request with the PDO connection, "this->pdo->prepare()" return a PDOStatement object
        $statement = $this->pdo->prepare($sqlRequest);
        // We execute the request
        $statement->execute(['id' => $id]);
    }
}